CREATE TABLE accounts (
      id INTEGER(11) NOT NULL AUTO_INCREMENT,
      name VARCHAR(20) NOT NULL,
      email VARCHAR(100) NOT NULL UNIQUE,
      password VARCHAR(72) NOT NULL,
      created_at DATETIME NOT NULL,
      updated_at DATETIME NOT NULL,

      PRIMARY KEY (id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;